const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Behaviors.Pin,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Timeline,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.video,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Shape3D,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.For,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Anchor: 0},
	{btn_main: 0},
	{btn_music: 0},
	{Tween: 0},
	{btn_restart: 0},
	{btn_sound: 0},
	{Fade: 0},
	{btn_changePage: 0},
	{aim: 0},
	{hits: 0},
	{memAngle: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Arrow: 0},
	{arrow_home: 0},
	{Physics: 0},
	{Body: 0},
	{Pin: 0},
	{bow: 0},
	{Wrap: 0},
	{cloud1: 0},
	{cloud3: 0},
	{cloud4: 0},
	{cloud5: 0},
	{deco_: 0},
	{deco_1: 0},
	{deco_2: 0},
	{deco_3: 0},
	{deco_4: 0},
	{deco_5: 0},
	{deco_6: 0},
	{deco_7: 0},
	{deco_8: 0},
	{deco_9: 0},
	{Sine: 0},
	{BALLOON: 0},
	{grass: 0},
	{handArrow: 0},
	{mountain_nw: 0},
	{sky_nw: 0},
	{tree_1: 0},
	{tree_2: 0},
	{Menu_ballon: 0},
	{shootX: 0},
	{shootY: 0},
	{ricochet: 0},
	{player: 0},
	{player_menu: 0},
	{Story_player: 0},
	{"9p_main": 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{Audio: 0},
	{bgPaused: 0},
	{Browser: 0},
	{fade: 0},
	{fade_story: 0},
	{intro_: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{shadow: 0},
	{skip_button: 0},
	{skip_hand: 0},
	{Sprite3: 0},
	{Story_king: 0},
	{story_text: 0},
	{Text_box: 0},
	{Solid: 0},
	{Tilemap: 0},
	{TimelineController: 0},
	{title: 0},
	{Touch: 0},
	{memPos: 0},
	{txt_btnLevel: 0},
	{txt_dispPage: 0},
	{txt_gameover: 0},
	{txt_instructions: 0},
	{txt_level: 0},
	{txt_reset: 0},
	{txt_taptocontinue: 0},
	{txt_ver: 0},
	{Video: 0},
	{warning: 0},
	{loader_bg: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Ballon_spawner: 0},
	{Info: 0},
	{Sprite: 0},
	{logosprite: 0},
	{Sprite8: 0},
	{inp_name: 0},
	{inp_mail: 0},
	{email_d: 0},
	{maild: 0},
	{Mouse: 0},
	{start_btn: 0},
	{Score: 0},
	{txt_score: 0},
	{txt_lives: 0},
	{"3DShape": 0},
	{Sprite2: 0},
	{restart: 0},
	{page: 0},
	{Lives: 0},
	{gameActive: 0},
	{progressLevel: 0},
	{currentLevel: 0},
	{levelsCount: 0},
	{Sound: 0},
	{Music: 0},
	{fadeTime: 0},
	{type: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	btn_main: class extends self.ISpriteInstance {},
	btn_music: class extends self.ISpriteInstance {},
	btn_restart: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	btn_changePage: class extends self.ISpriteInstance {},
	aim: class extends self.ITiledBackgroundInstance {},
	Arrow: class extends self.ISpriteInstance {},
	arrow_home: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	bow: class extends self.ISpriteInstance {},
	cloud1: class extends self.ISpriteInstance {},
	cloud3: class extends self.ISpriteInstance {},
	cloud4: class extends self.ISpriteInstance {},
	cloud5: class extends self.ISpriteInstance {},
	deco_: class extends self.ISpriteInstance {},
	deco_1: class extends self.ISpriteInstance {},
	deco_2: class extends self.ISpriteInstance {},
	deco_3: class extends self.ISpriteInstance {},
	deco_4: class extends self.ISpriteInstance {},
	deco_5: class extends self.ISpriteInstance {},
	deco_6: class extends self.ISpriteInstance {},
	deco_7: class extends self.ISpriteInstance {},
	deco_8: class extends self.ISpriteInstance {},
	deco_9: class extends self.ISpriteInstance {},
	BALLOON: class extends self.ISpriteInstance {},
	grass: class extends self.ISpriteInstance {},
	handArrow: class extends self.ISpriteInstance {},
	mountain_nw: class extends self.ISpriteInstance {},
	sky_nw: class extends self.ISpriteInstance {},
	tree_1: class extends self.ISpriteInstance {},
	tree_2: class extends self.ISpriteInstance {},
	Menu_ballon: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	player_menu: class extends self.ISpriteInstance {},
	Story_player: class extends self.ISpriteInstance {},
	_9p_main: class extends self.IWorldInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	bgPaused: class extends self.ITiledBackgroundInstance {},
	Browser: class extends self.IInstance {},
	fade: class extends self.ITiledBackgroundInstance {},
	fade_story: class extends self.ISpriteInstance {},
	intro_: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	shadow: class extends self.ISpriteInstance {},
	skip_button: class extends self.ISpriteInstance {},
	skip_hand: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Story_king: class extends self.ISpriteInstance {},
	story_text: class extends self.ITextInstance {},
	Text_box: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TimelineController: class extends self.IInstance {},
	title: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	txt_btnLevel: class extends self.ISpriteFontInstance {},
	txt_dispPage: class extends self.ITextInstance {},
	txt_gameover: class extends self.ISpriteFontInstance {},
	txt_instructions: class extends self.ISpriteFontInstance {},
	txt_level: class extends self.ISpriteFontInstance {},
	txt_reset: class extends self.ITextInstance {},
	txt_taptocontinue: class extends self.ISpriteFontInstance {},
	txt_ver: class extends self.ISpriteFontInstance {},
	Video: class extends self.IWorldInstance {},
	warning: class extends self.ITextInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Ballon_spawner: class extends self.ISpriteInstance {},
	Info: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	logosprite: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	inp_name: class extends self.ITextInstance {},
	inp_mail: class extends self.ITextInputInstance {},
	email_d: class extends self.ITextInputInstance {},
	maild: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	start_btn: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_lives: class extends self.ITextInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {}
}